name: 'Regex Replace'
description: 'Allows you to perform a regex replace in your repository files'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  regex:
    description: 'regex to apply'
    required: true
  flags:
    description: 'flags of the regex'
    default: 'g'
    required: false
  replacement:
    description: 'replacement string'
    default: "$1"
    required: true
  include:
    description: 'Files to be replaced'
    default: '.*'
    required: false
  exclude:
    description: 'Files not to be replaced'
    default: ''
    required: false
  encoding:
    description: 'String file encoding'
    default: 'utf8'
    required: false
outputs:
  value:
    description: 'regex replaced in your repository files'
runs:
  using: 'node12'
  main: 'index.js'
