name: Build

on:
  - push
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: mingjun97/regex-property-action@test
        with:
          regex: '"version": "([0-9\.]*)",'
          replacement: '"version": "${1}-test",'
          include: 'package.json'
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            *.json